### ISSUE TITLE
UI scale

### ISSUE THREAD

**Issue by DaneelReventelov** [alekslt/DSPPlugins_ALT#1]
Can you add a way to scale the ui for larger monitor?

**Comment by alekslt** [comment]
Hi, not really sure what you mean, since that's the actual job of the UiLayoutHeightFix mod.
By running the game with that plugin once, and then editing the configuration (manual install= %steamapps\common%\Dyson Sphere Program\BepInEx\net.toppe.bepinex.dsp.uilayoutheightfix.cfg) or through the mod manager, you can set:
UILayoutHeight = 1440
         OR
UILayoutHeight = 2160

are you requesting a larger value than 2160?

**Comment by justin201802** [comment]
No use to set UILayoutHeight.
Game Resolution set 3840x2160
and UILayoutHeight set to 1080
but this mod‘s GUI is very small.

![20210222212650_1](https://user-images.githubusercontent.com/36726475/108714773-ef742100-7554-11eb-90e7-43d97a36bf7b.jpg)

**Comment by yushiro** [comment]
No use to set UILayoutHeight.
Game Resolution set 3840x2160
and UILayoutHeight set to 1080
but this mod‘s GUI is very small.
![20210222212650_1](https://user-images.githubusercontent.com/415386/108715622-14b55f00-7556-11eb-9eb4-5aa2c2742ee4.jpg)

**Comment by yushiro** [comment]
code reference
https://bensilvis.com/unity3d-auto-scale-gui/

**Comment by alekslt** [comment]
Thank you @yushiro :) I'm new to Unity UI and scaling yes, so I appreciate your help, PR and detailed explanation.
@DaneelReventelov I will make a release as with this fix as soon as possible. Ideally I will rewrite parts of this to use the normal Unity UI, and not immediate mode, but that's for the future.

**Comment by alekslt** [comment]
Fix available in release 0.5.1 https://dsp.thunderstore.io/package/alekslt/MineralExhaustionNotifier/0.5.1/
