### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dorky106** [alekslt/DSPPlugins_ALT#9]
No idea if this mod is still worked on or not but here you go.
MissingFieldException: Field "UIGame.dysonmap" not found.
DSPPlugins_ALT.MineralExhaustionNotifier.OnGUI() (at <2b45917b92674dc39219c3e8527c2643>:0)

**Comment by Fireball14** [comment]
Same here

**Comment by DocHogan** [comment]
Same.

**Comment by alekslt** [comment]
Hey, a fix for this is in main/master now, but I need some time to test before a release. Will probably update thunderstore this weekend ASAP.

**Comment by L1iMa** [comment]
Any news or update on this?
Appreciate your work!

**Comment by Dorky106** [comment]
what is the status on this?

**Comment by Renthal** [comment]
Is there a way to use the master version?

**Comment by alekslt** [comment]
Released the new version now. Sorry for the communcation blackout, but I have just plainly not had time to work on or play this game for a bit. Starting to get into the grove again now though :)
The update is released on thunderstore, and is also available as a github release https://github.com/alekslt/DSPPlugins_ALT/releases/tag/MineralExhaustionNotifier-v0.5.4

**Comment by alekslt** [comment]
Since I had some changed in the master/development version, I also included these, so hopefully there aren't any breaking changes besides fixing what actually broke this from working with the current release.

I know about the perf issues, and one of the longer term moves was to get this using the normal Unity UI (scene graph), but that is a major undertaking.

Anyway :) have fun with the game.
